name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3,15 * * *'     # Runs at 3 AM and 3 PM UTC
  workflow_dispatch:           # Allow manual runs

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # Needed to push changes
      actions: write           # Needed to trigger other workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # Fetch full history
          ref: main

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Taoshix/RaC3AP.git
          git fetch upstream

      - name: Fetch all branches from origin
        run: |
          git fetch origin
          git branch -r

      - name: Sync upstream changes into main and staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          changes_detected=false

          for branch in main staging; do
            echo "🔄 Syncing branch: $branch"

            # Try to checkout local branch; create it if missing
            if git show-ref --verify --quiet refs/heads/$branch; then
              git checkout $branch
            else
              echo "ℹ️ Local branch '$branch' missing. Creating from origin/$branch (if exists)..."
              if git show-ref --verify --quiet refs/remotes/origin/$branch; then
                git checkout -b $branch origin/$branch
              else
                echo "⚠️ No local or remote branch '$branch' — skipping."
                continue
              fi
            fi

            before_commit=$(git rev-parse HEAD)

            # Merge upstream changes if upstream branch exists
            if git show-ref --verify --quiet refs/remotes/upstream/$branch; then
              git merge upstream/$branch --no-edit || true
              after_commit=$(git rev-parse HEAD)

              if [ "$before_commit" != "$after_commit" ]; then
                echo "✅ Pushed updated $branch"
                git push origin $branch
                changes_detected=true

                echo "🚀 Triggering build for $branch"
                gh api repos/${{ github.repository }}/dispatches \
                  -f event_type=trigger-build-apworld \
                  -f client_payload="{\"branch\":\"$branch\"}"
              else
                echo "ℹ️ No new commits for $branch"
              fi
            else
              echo "⚠️ Upstream branch '$branch' does not exist — skipping."
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
